name = "ExtTreeMapLemmas"
version = "0.1.0"
defaultTargets = ["exttreemaplemmas"]

[[lean_lib]]
name = "ExtTreeMapLemmas"

[[lean_exe]]
name = "exttreemaplemmas"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.22.0-rc2"
